// AUTO-GENERATED by scripts/scan-assets.mjs — do not edit by hand.
// Regenerate with: npm run assets
//
// Records every image currently present under public/assets. Semantic keys in
// data/assets.ts consult this to decide between a real image and a neutral
// missing-asset fallback.

export type ManifestEntry = {
  width: number;
  height: number;
  blur: string | null;
};

export const assetManifest: Record<string, ManifestEntry> = {
  "/assets/case-studies/uniform-apron-program/detail.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAADQAQCdASoQABAABIB0JZwAAvkPFjkeAAD+6+QicmVQ9gDgAAA="
  },
  "/assets/case-studies/uniform-apron-program/fabric.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAACwAQCdASoQABAABIB0JZwAAudflaoQAP7ufyqUnHN4UAAA"
  },
  "/assets/case-studies/uniform-apron-program/product.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQABAABIB0JZwAApQdlEIXIgAA/vN7fPCrKlmnNCD15KNrPjMookK9/OASdhamljAM1fvIpFOZRnUvI5z5btK1IoAAAA=="
  },
  "/assets/development/fabric-swatches.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkABIB0JQBOgBbr1JdwAP7nOb8Lms1Dknv1J1yg56mAcp8eadif0PofvpYVKqa1MxLP8qiN7hiSb84AAA=="
  },
  "/assets/development/measurement.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkABIB0JYwCdADa7ASagAD+wHBQ3igJ1Ziu3Y8zvrrxMxux66aBEuGTi9suCwOZbEjNKsf0/vWHwSgAAA=="
  },
  "/assets/development/pattern.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAkABIB0JQBOkCYiSHQiAAD8Nl5QHFuk0tDCvI4oPoDd897gFnK5B+KmS5kQAAA="
  },
  "/assets/development/tech-pack.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkABIB0JQBdgBU9ymU+gAD+5oOAzHRhSBOmS/QY+MWet18ObsQT+tnsr8OaUFHp0FCr5+BiNPODAAA="
  },
  "/assets/development/trims.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkABIB0JZwAAlE+RMAA/OGB7/PQ6IzkLQR92mjilerjxvLw8jJ8wDzpByJJ6iDOdpeGAdz31zTC/rSNd44AAAA="
  },
  "/assets/export/carton-marking.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoQABAABIB0JbACdAEfbElMZmOJAAD+6zJ2ceQYUMX0GXOE/SiZvHXWcaBwudoaBvD3hmI+1KeCVX4go7uTLMQAAAA="
  },
  "/assets/export/cartons.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoQAAkABIB0JYgCdH8AFXk6kXIAAP7vy55mQjJ+LaAWCsorMrL8TZ/4rkllpAFFPkgAAA=="
  },
  "/assets/export/container-loading.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkABIB0JZACdADMsXXriAD8jDLEBp9ecR21S5o1kH3hSUQiCpRys5TKFJhSbrnAOycHkqZSmaO0pvYB+JS+4IYAAA=="
  },
  "/assets/export/warehouse.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAkABIB0JZACdAEQz7zowADJcBH6KtwUctMPWcx8uPG04S7NtLwzRfSbsDAA"
  },
  "/assets/fabrics/canvas.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAABQAQCdASoQABAABIB0JZwABDOAAP7p7LzgQAAA"
  },
  "/assets/fabrics/cotton-pique.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7vTEAAAA=="
  },
  "/assets/fabrics/fleece.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7wGCAAAA=="
  },
  "/assets/fabrics/mesh.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAABQAQCdASoQABAABIB0JZwABAAAAP7tBxvugIAA"
  },
  "/assets/fabrics/polycotton-twill.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAPzEgQAAAA=="
  },
  "/assets/fabrics/polyester-performance.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAABQAQCdASoQABAABIB0JZwABAAAAP7uQxDy8IAA"
  },
  "/assets/fabrics/rib.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7vckAAAA=="
  },
  "/assets/fabrics/single-jersey.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7lCDCAAA=="
  },
  "/assets/fabrics/softshell.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAABQAQCdASoQABAABIB0JZwABAAAAP7u09Dy8IAA"
  },
  "/assets/fabrics/woven.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAABQAQCdASoQABAABIB0JZwABDOAAP7p7LzgQAAA"
  },
  "/assets/factory/cutting.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoQAAkABIB0JZQAAp2l5vmQAP6muRSHGBVkqP4k14BVnOPCw/LfDOIltoV9kMe+CAAAAA=="
  },
  "/assets/factory/embroidery.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoQAAkABIB0JZwAApOpvSlCt6AA+pGpPqEwC2N+Z4LRx+5ICptG8OrLUe3EARK4wAA="
  },
  "/assets/factory/fabric-inspection.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAkABIB0JYwAAxPH+OyxHYAA/r6CxF8aemJfB4A2duLBs5iNCZX5bo0tYsV42ese8lLjHm2AAA=="
  },
  "/assets/factory/finishing.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkABIB0JZwAAvh5r3m+MAD7IuqH6Syw459YlkEOi1iFcDOlfJLhPCc0iw9guFZny0AchJUIAA=="
  },
  "/assets/factory/packing.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkABIB0JQBOgBLpU7cAAPsiwaac0DN3eM6hKxIaCnViU3E2xliWY/GFkS/RduICBjczqDVhxgAA"
  },
  "/assets/factory/quality-control.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkABIB0JZwAApv1olqAAAD+wSKlRCico/Bbp//Jta5CDYkF9b/HVQ/YQA9sf4EjwXKYLBUAGnKCHxGHAAAA"
  },
  "/assets/factory/sewing.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkABIB0JYwC7AEO2zCrVIAA9G2FNjNAWk8et60NYa/QRqQr5f8yKqJt3RvMpvNa6Nlw+HBdzy9gAAA="
  },
  "/assets/hero/hero-sewing-01.webp": {
    "width": 1920,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkABIB0JYwC7AEfUKOKQAD925yORHgZ1oSm4aSiTSGbSXb505d/Y8EdtJlM/ULdmWhKP4uEAA=="
  },
  "/assets/products/aprons/apron-black-front.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQABAABIB0JZwAAn/8QhOenF4AAP7zgHol7nLbSmFPr5j2jOUPTjQsxu5yHKwMTl/g8RQQ/JRjF2WysgqHhDO1MX+lMVAKAAA="
  },
  "/assets/products/aprons/apron-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAPzEgQAAAA=="
  },
  "/assets/products/details/apron-construction.webp": {
    "width": 1400,
    "height": 933,
    "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoQAAsABIB0JZwAAvenr5LfIgAA/u1LGFT2yt5x1YYBsVd9yhgiv5HRQAA="
  },
  "/assets/products/details/bottoms-construction.webp": {
    "width": 1400,
    "height": 933,
    "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoQAAsABIB0JZwAAvenwFScYwAA/u1LGFUDIyURljrVuK1L2biuQzNasIAAAA=="
  },
  "/assets/products/details/fleece-construction.webp": {
    "width": 1400,
    "height": 933,
    "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQAAsABIB0JZwAAujcE8EYAAD+7VrVqJvERohGiPgB9csZVfR6IbTfOEAAAA=="
  },
  "/assets/products/details/outerwear-construction.webp": {
    "width": 1400,
    "height": 933,
    "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAsABIB0JZwAAujdXo4rwAD+7VrVqJvERogRi0v+BqDHL7rvt0AEAAA="
  },
  "/assets/products/details/polo-construction.webp": {
    "width": 1400,
    "height": 933,
    "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoQAAsABIB0JZwAAujcE8EzgAD+7VrVqJvERohGk4ZnN8z67DFTOgUIrHAAAA=="
  },
  "/assets/products/details/tee-construction.webp": {
    "width": 1400,
    "height": 933,
    "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAQCdASoQAAsABIB0JZwAAvenr5LfIgAA/u1LGFUDIyUR4YH3boTOoecldjHAAAA="
  },
  "/assets/products/details/woven-shirt-construction.webp": {
    "width": 1400,
    "height": 933,
    "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAsABIB0JZwAAvenoFf9IAD+7UsYVPbK3nJON+AG+Z1+VFVXcwQAEAA="
  },
  "/assets/products/fleece/fleece-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7wGCAAAA=="
  },
  "/assets/products/photography/chino-beige.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABwAwCdASoQABQAPymEulIuKSYisAgBwCUJZwDDNC0gDWEr4YAA/u0xB/46/Qupe88fzIMHNoaMr+JcOfIFqRxgxUiTr7BAAAA="
  },
  "/assets/products/photography/denim-utility-jacket.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoQABQAPyl8tlIuJ6UisAgBwCUJYwDCgCBS7y2BqWC1YTYA/uqW/OHB82+/XROkedE5GbtNKeOXlHJARlKYKBP30EnOPLa5vI3C8RCrwpdEikF5BBkhigxoAAA="
  },
  "/assets/products/photography/denim-work-shirt.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQBACdASoQABQAPyl8tVIuJ6UisAgBwCUJZgCdMoMxgDiwN60C4bWVl3mgAP7qlN3eOFSUvaUNgcYimUbczXl+IEvhRz9iA3+GZfaLCrpGQf7avvyi/HitCc7ZS8okkzpvVvMo/eaGmPu+SEsnxwSew7gksOcdHkAAAA=="
  },
  "/assets/products/photography/henley-green.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAwCdASoQABQAPyl+tlKuKCUisAgBwCUJZQAAUYALmTb2sEAA/ufuGMwVuAS5WJRrXWJmPzvvJE8hyDMC1sZ6DOIkae9kHobd3iCNl5yn02CDHqQzRl1BCXnvh116V6L212AA"
  },
  "/assets/products/photography/henley-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZQAAUYBlFx96QWCAAP7n7BZsjv4t+DFO1eepbt3IxFQy/Zd0UsPZXvDi9D0UUbcTbHpy7s3KxB7O8946yuOFpNpWP1DYqAA="
  },
  "/assets/products/photography/henley-tee-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQAwCdASoQABQAPyl+tlKuKCUisAgBwCUJZQAAUXgvNR4p44MAAP7rJbJWqGiovd5u2uLAOSFjGoHbHYHXMHg1F97dIaHtM1TIPlemEg+2HJS9h+TLO1ZH1Wk6xaiDsAAAAA=="
  },
  "/assets/products/photography/henley-waffle-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABQAPyl+tlKuKCUisAgBwCUJYwAAUOVq46REDF9jyAD+6pI/KhsHvJ2r296A4kOotH2X8j2VECoDDVQfS8I+z5K1JuI4TPqRi0QT4oqHnumqp4scAAAA"
  },
  "/assets/products/photography/hoodie-black.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAV7H62PUPIkg0XcAA/uqIWae6lRYEDJF7eEDswwp1cTV05kTZjCm/tXow+DVLS+Gsfv0gf9JC+qcA9bRVKjVmZf+TsO2EKZo4AAA="
  },
  "/assets/products/photography/hoodie-heather-graphic.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwDGfBufffcR3nEZTNwA/uqVJv6okmRpYkiwigkFJRmHgYIF9TZszmlAmlLrNusP0K16vDo2IA1txOgUAA=="
  },
  "/assets/products/photography/hoodie-navy-alt.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJYwAAXrV/Avqsen5W8xQAAP7qiEHCpVa1UARiABCxZJUivzTAwYK3c+BvnWCcV+1DykGI2fh5o4ueiVGtAkA/7GLHcBBCJ2YdRkG/4NLSeMuwAAA="
  },
  "/assets/products/photography/hoodie-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQAARmYI2v6ko5uPQAD+6n+8lk0AD0lq5PNK4AcSwiqbDP2L1H0ZsDvkrpubkOi0A9QE2x9II+lqJRFzgnav/E285r3EHyUk/iGRppmLSliAAAA="
  },
  "/assets/products/photography/hoodie-pink-graphic.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACQAwCdASoQABQAPyl+t1KuKCWisAgBwCUJYwAAW+tcWg4dCGAAAP7qjlCd/ymQcRx3JzCSLzU7IIAA"
  },
  "/assets/products/photography/hoodie-white.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAW/FEJFmgAP7qizA4rZ4QTMFb0MkryteYIUEAAA=="
  },
  "/assets/products/photography/jogger-grey-graphic.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAUX9Y7mbxSleoWAD+6pGXV8NAVv1b02FjwioBJNW1N8iIhZQCxDKJP8ukMAAAAA=="
  },
  "/assets/products/photography/lounge-pant-grid.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoQABQALumUymUkri4uDgDoSzgABSTci6/N30TAAP7zgnAXXUNn1pwEwCsweE3WhwFoMGKa4AAAAA=="
  },
  "/assets/products/photography/onesie-white-print.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADwAgCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAerHYAAD+7u3fngAeQTCO2VAAAAA="
  },
  "/assets/products/photography/onesie-white-text.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAAAwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAidzPk7KgAP7u7d+NWAAAAA=="
  },
  "/assets/products/photography/pant-camo.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQCo9B4bYEC2UpsKWAD+598ZG7uaN3v8/W1TQurxtI8DmvsZJAneygHwvkJDy9wf8tOr/08/piOxpYYXnP1Gv1PiWIA7CSuutHswAAA="
  },
  "/assets/products/photography/pleated-trouser-khaki.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoQABQAPymAulMuKCYisAgBwCUJZwC2yB3Y7vLByxLagAD+6pcpkWLVRY8LT4UNtakkfsop4DgUno2TYGp+wMv7sTJGXRm0I6O3dgAA"
  },
  "/assets/products/photography/polo-black-crest.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAV7HzfgFkrNJVwAD+6pXWZShVTIbsPyNRbtZlR83ubcLfNOCHNrRCmUQO17/+aWv0utz7tcxY/rAqvAbfPrpXd2CrnAAAAA=="
  },
  "/assets/products/photography/polo-black-embroidered.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAATGNMoebRYNM+AAD+5+4YzW+RUxO+sfAZ/vZKbwJtewAlokjK7n4TNWPXTyx01Eyh9rLGWa/5XpSyRnAeSgoAAA=="
  },
  "/assets/products/photography/polo-black-service.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAYdKP3YLJhJBwfOAA/uHjP4AlHMhJrN9+DhtUmjBD5bU85p0n59CeJEWtz6Cd90Isn+b2Nl1Cs37n6UqJTvAkWAAA"
  },
  "/assets/products/photography/polo-cream.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAAAwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAiestZI0AAP7umKIO9tHIOxmmaGXI4vTYPjcFgOtCAAA="
  },
  "/assets/products/photography/polo-dress-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoQABQAPyl+tlIuKCUisAgBwCUJZwDG9BI3mcwSJCmiYAD+6pfN8O50wgGUzTKi3UTqeMWYMFdoS0zGo/RDeYtK9VZ3PXtzRcKeROyzfawrLK2llZrXjGZHcB82HODl8K2MwhZgxgAAAA=="
  },
  "/assets/products/photography/polo-green-ribbed.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZQDE2B7BFm9SvIjU2pXAAP7rJbJWqGdYmpzd2KQE9cTlWBP1Yns35TajWK/JcPcBMpNvazWU+GHAWTTMFgjHEKsAAA=="
  },
  "/assets/products/photography/polo-lime.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoQABQAPyl8tlIuJ6UisAgBwCUJbACdACB/0UXXFELoAP7qlaK3spoCsPjuyveQ6F8UAuS3rzrWrJTFDAGRWfoaScJpYwyoKNdEeC9fGYczMupPuPhAAAAA"
  },
  "/assets/products/photography/polo-maroon.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAQBACdASoQABQAPyl8tVIuJ6UisAgBwCUJbACdACPytWfLsUkSq4UuAAD+5+4YzWDDKHKdVXoYNyttQmvK5hbggzsQYRtEZPFcbEmlojV/mmOxkonpMlR/iXBsjJGSJsGMIce2yBaxth9txSMyAAAA"
  },
  "/assets/products/photography/polo-navy-corporate.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBACdASoQABQAPyl8tlIuJ6UisAgBwCUJZwDDNCPwHQ72Gjn7cRkWpQAA/uHjP4Al0pmCb5gCjpj5h/FWJaB2SgQMkrpf8fULhvdVJmrSy5L464ePD5uhBnmcC6ezHHa2iwAA"
  },
  "/assets/products/photography/polo-navy-embroidered.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoQABQAPyl+tVKuKCUisAgBwCUJQBOgBH1RkKr7xXCAfWQCwAD+5+4iYFVPlB45teJC6S4hvcvJqs6l73rvarpJUPhOin4AaxN5R9ovKqHo/7/yEeSZhgQkIbuBjg04AAA="
  },
  "/assets/products/photography/polo-navy-grocery.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoQABQAPyl+tlKuKCUisAgBwCUJZwDKABnPAyCx4F04rAAA/uqii88mONvATsTCQX42AZ0oYQgt6Ok/x9y1jz4900S0x3X+3Ep2fyyxLBnOxlwsNdhYl0SziAAAAA=="
  },
  "/assets/products/photography/polo-navy-tipped.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQAAUyYB6m2gLzrWAAD+5+4YzJTs4d7LitlYvKRUnMvQCGoM4e1/bydG58Ya7flvcALz4olJFJDDk6Qgs6NlB+rv7Uv9XI9hs4Sd4CAAAA=="
  },
  "/assets/products/photography/polo-red-colourblock.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBACdASoQABQAPyl8tVIuJ6UisAgBwCUJbACdB2gAOsN7CHIorRTp9TAA/uqIQN/t2hOiGAIuNKtrYWDJTj7S/nq30hYgz5AEfxfNXGoYf5FgSMNufej3VTvKBBP4uDdS33EgooC+y+vqiT2smFDEh7vmVmZBGD9MmbHeG0AAAA=="
  },
  "/assets/products/photography/polo-red-grocery.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAABwBACdASoQABQAPyl+tVIuKCUisAgBwCUJbACdMoLUABR4e15hfGwXr++nAAD+4eM/gHxQ+kxr2fJT1XvCPx0Z8EwxzsJwdzvpNzhDUHKffdEt76XtoYQzS9PfmHx8SredqbT+vbok91KCTSGvqXChN85v1ki9jHudRBQOGcAAAA=="
  },
  "/assets/products/photography/polo-red.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAAAQBACdASoQABQAPyl+tlIuKCUisAgBwCUJbACdACBTafYVqsvBwVxpgAD+6n5tno8Hj6OlrbM/cvcyPcFVqIPllWxX8/lNe8wgukR5eWJfupb74d6XRPLalHZvNXMvbygyrD45jSFzQOAcJkEYP0JVdngoAA=="
  },
  "/assets/products/photography/polo-royal-embroidered.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoQABQAPyl+tVIuKCUisAgBwCUJbACdMoAChVqDxkLB5c0hAAD+6n+XVyHL9jkorIveODcLq355fNFeogABja78zMqwkwHXKWbcH8sUPLDP2uybyGCneduIVdqCUyCWJtlBHXm5Y4GgAA=="
  },
  "/assets/products/photography/polo-taupe-long-sleeve.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoQABQAPyl+t1KuKCWisAgBwCUJZQAARj8Co/9ox+AA/uqHYj+UvBTwrK7Jh3D4mSMd3moN9Bp638AjdNipALOtYjL61LyublkJmGU0AAA="
  },
  "/assets/products/photography/polo-white-embroidered.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAgCdASoQABQAPyl+t1KuKCWisAgBwCUJZwAAik/AAP7ulgnMU8ovoWuJgNO2vMEKCAAA"
  },
  "/assets/products/photography/polo-white-tagged.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACQAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwDLLCHhv/GnO0sAAP7qfAc+feQ7WWLW5ozUAAA="
  },
  "/assets/products/photography/polo-white-tipped.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAUTR4tt8USoAA/uqV1LLiRgaghwe1UYwc1ZJsmVno481m2BDgAAA="
  },
  "/assets/products/photography/polo-white.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAAAwAwCdASoQABQAPyl+tlKuKCUisAgBwCUJZwAAW+qhUgUAAP7qZ9QC7W3zFat0XZHbXmgA"
  },
  "/assets/products/photography/polo-yellow.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAwCdASoQABQAPyl+t1IuKCWisAgBwCUJZgCdACHhW31nwq09jrMAAP7qjlCZ1s1BtWw2G2kZ9vyLIlqdkJ1GFKK4AAAA"
  },
  "/assets/products/photography/scarf-camel.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABQAPyl+tlIuKCUisAgBwCUJZACw7B97/UuCK8YkSFPgAP7rJY3r6oxkj5VDQSRmcEh46zx2nVDPI0N6z0hypW4BefH/2xwxuL9BkApgZVKkqyEnagAA"
  },
  "/assets/products/photography/scarf-herringbone.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAWnv57gRtJZXxed+AAP7gzfPEUAu1nPYkZTugwNUSxohhmjGEinwmSt9SyjzVXDJILEMzbgzbwHJ2p55NU1HsNBslqznUfhQAAAA="
  },
  "/assets/products/photography/scarf-navy-looped.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQAAXdPPuCJqMajBAAD+15Utoaav7H+BSO45zK9zy43DniMrLX3hCAR05GYzP49xeMoP+usYUDr7ve0A3b6Ns2WteHCHGN9WSwm0aKfAAA=="
  },
  "/assets/products/photography/scarf-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABQAPyl+tVIuKCUisAgBwCUJZwAM4AIJN1wbXexzE0PkagAA/uqU05gBegZiVDUUxfCuSTifPjFvY1r/XP/TnxRZYvhmLzRjXCB7w/uvfh0dPXdnmFT0iAIMrpi87TRHQOvyqEecyFNYQlrAxIQA"
  },
  "/assets/products/photography/scarf-plaid-maroon.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQAAXdGh/3Tei6vDdgAA/tYZTQU6JhA+j0E8aoZUDurXKABnEG/KygXUIjbu07qVWHp2+AwjPCYVr1oEiOvM74jtmrxr/HaYogFrCAA="
  },
  "/assets/products/photography/scarf-plaid-olive.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwDMHCK5mazCOXFD8HgA/sl2nVlb59uOrxHdgbXXc/e5/bNf3xX2Dmkxyjf68wGu4H6xIMOmRqLb4DeVpd88SaGLpk9QPFAAAA=="
  },
  "/assets/products/photography/sleeveless-hoodie-black.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABQAPyl+tlKuKCUisAgBwCUJZwAAVUc8AUcFvpUloAD+6pUm9jit7MeLBUli4s9fJ4ckjtWYhjtM2oPqMLnqGJ6OnYLSt7Itx7KttF6pfsDkuczpjgAA"
  },
  "/assets/products/photography/sleeveless-hoodie-white.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAW/ChD3mgAP7qjlCdTwf9n84MyMK3lK3Aa47zmEd4ruCQAA=="
  },
  "/assets/products/photography/sweater-red-striped.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJbACsAB4kiWhWFIzuzVrIAP7qlaU0S4iOF8UmMFy83Uxi3IIqxYdFNEDhWjap3CT3XbV7OXei5nkxZl7IpXrQdWl8FBpbxifhDnaAAAA="
  },
  "/assets/products/photography/tee-grey-branded.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAVMCb67CCSzMs80oAAP7qw2iG2fhPcIzPdA4S+kmzLYqA8GyMVyGnehasrLIm8WzQAAA="
  },
  "/assets/products/photography/tee-grey-graphic.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoQABQAPyl+tlIuKCUisAgBwCUJZwAAW6gp5XxcS5dAAP7qjp3xlMA+sPwL+jEeigl7ezbavOjt5bCXwjYWT+dAhVAQAA=="
  },
  "/assets/products/photography/tee-heather-graphic.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAW/CLmyumUau/CbAA/uqOnfGb9LJSxBmIYFNx938w8vBgEhokxPAABRD468WAAAAA"
  },
  "/assets/products/photography/tee-pink.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAwCdASoQABQAPymAtVIuKCUisAgBwCUJbAAAXeplMyNlrrwA/ufr3HGUoQGbmUZGYfm9nrsS0tWP9S/JEKRJ0r9rN8PqsB3jFUlg1KFnslq03W7aTVr0QAA="
  },
  "/assets/products/photography/tee-sky-blue.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoQABQAPyl+tlKuKCUisAgBwCUJaACdAB2QN4rzt7OwAP7qlXy+r5U8D41hHhBMlpXhNNGK4UQVfI5bHLNhG2kdrvtV5b6Orc99N2I6wNV/4JXywAA="
  },
  "/assets/products/photography/thermal-sage-alt.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoQABQAPymAtlKuKCUisAgBwCUJZwAAW49Pt8AESamLAAD+5+4Oe/kbr8S1ITUM1FPjnh0MJ3F9fR79fBbccYHY1oHjIaW2gAAAAA=="
  },
  "/assets/products/photography/thermal-sage.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAUXoTuHCUJzSCiAD+6pV/7x/HXsgY1dyPFzzefWcm3964HQ4sTpK5/LJnD3LyP61lgAAAAA=="
  },
  "/assets/products/photography/utility-bomber-charcoal.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoQABQAPyl+uFKuKCWisAgBwCUJZwAAV4RyIoR6ImkHwWQA/uqIQOFIJSp9TtfGZAz5jV3sGqosHj0lFtJuXuxdi1T12KYEYTRepE/HXOu2wQmz+XEAAAAA"
  },
  "/assets/products/photography/vest-orange-printed.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACwBACdASoQABQAPyl+tVIuKCUisAgBwCUJbACdL14UCDAAMAQ2LRLwb5bsXSCAAP7n7Attgubaf50YVpjkQTzBalVrMqee6HC6PaWWKAcsdS2sN87sV0xXgYAZK6AKKqMIQeCtzGwOjOOWEFUldyfh29XZagAA"
  },
  "/assets/products/photography/work-vest-orange.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoQABQAPyl+tVIuKCUisAgBwCUJbACdMoLUABOuyOUmxt4wAuQA/ufsS9C+V3xFB/zYMu7LGHBDnKdpchmgNoc4T4rxZH7bqXbTJQGXh4wYHJlkJuf6TEcQRayanqxzJ3TumEeqNAnkKoqZkJ4ON6swnAAAAA=="
  },
  "/assets/products/photography/zip-hoodie-grey-graphic.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwDLLCLWYIgaw2lT/gCAAP7qh2eYtbn/fGPA3vgbWuM6rAKZCig8oqV5jqtsf7pa3uJyodqdJfO3meDoMNM57dgIAAAA"
  },
  "/assets/products/photography/zip-hoodie-grey.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoQABQAPymAtlKuKCUisAgBwCUJZwAAUrmB5XgTf+DOAAD+6pbmvXiFIkyM+1LC6r2LvQ1HgvcReYbiktEAQAAA"
  },
  "/assets/products/photography/zip-hoodie-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZQAAV7H7/YLTu3rFoAD+6pLFDLYUt6YcJ9SOTTkGWqjqS/GcnXXIQRbN/I1fjGy3MohacRs/ik+NJYXw6F+Y/9pZTGKJ8A6A5XO04c0IAA=="
  },
  "/assets/products/polos/polo-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7vTEAAAA=="
  },
  "/assets/products/renders/bib-apron.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSIkAAAABgFvb1rKI2N3dQsoh0jLcXUpwt0YcJrNG4PvfDYf/rZkOImIClH/sVqlcKo55OJ+P7awL8OHmRD6BnygnJwFSVS0XvxIRPdIytsxGCCEOeec7paoJAAOdUr4mXi/RUzLLJEnU4ZQAgFUmImLVxPMpepwGAPQ59V89Tux4vZ6SHLXb7/fp3ij+HQBWUDggLgAAANACAJ0BKhAAFAA/KX62Uq4oJSKwCAHAJQlnAACJ9AAA/u9VES7xLdw/SooAAAA="
  },
  "/assets/products/renders/button-front-shirt.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRioBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSLgAAAABgLJt2/JU/bJvOGR398gfWKNyrKPRHRrNpbkld7I2d21z394rfoJFxARo/2ey1WazpqgoXrq12+9WyhUKDn2fHs+n76RYbhjCggiMyK1DJCSADYMk7hSIAlwmS1Jfo+FwCCLRj2xJjcvhQghcdk+tpC5y/QnwdSXqJW3sPkteduiTzDL+gBA8jzKn1Wp1nRfN9wDPTZf9Rq1Wa0zLuwbBfWFarFbW1DA1NTXVatGqNJlMJq2s5tcBVlA4IEwAAACQAwCdASoQABQAPyl8tlIuJ6UisAgBwCUJZwAAW+zexJACPgQAAP7ujqFSaf9W3CuXg/cIDkSs1p49mLXQoD4+QQ9FhfB+rFD8cAAA"
  },
  "/assets/products/renders/chef-beanie.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSGUAAAABcFNt27L8s/sfQ/lCcAjhFgM2JvcCbLDRxvkC4P6u7+8FImIC2HQq2WYrpwZQO2eAc9/0yz8AAJ5VvwWgS78VtpZ82lif9e380Ilf/4vO/XqABihsKKV01/ATLUIIcTS/dDOxAwBWUDggKgAAANACAJ0BKhAAFAA/KX62Ui4oJSKwCAHAJQlnAACJ9AAA/u96Wi2kOAAAAA=="
  },
  "/assets/products/renders/chef-coat.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRkIBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSLkAAAABgGLb2rLlz+4uyd3/H4kMgsoEPLpDo7k0KsmdrM1dmzvv+9z4CTaBiJgA5f/0VDc3V3tlZGdOzs5O5kskkiv0+vz8QusZsT6AAV+EfrEpCDlhWiMwbwAcYMCOQ+C74IxAX5/8OiIof7x/JIAe754rBJVs74YD/HaXqgSNWDgDgPN5dAomMHTMAHY2gEmlUqlq2a47AoCz2p0urVKp1Prje4KjlN+kFNVVj46OjjYYlDJ1Op1OKar4dQBWUDggYgAAABAEAJ0BKhAAFAA/KXy2Ui4npSKwCAHAJQlnAABb8G8z2kKLSer20eUAAP7uklIYWCJJSF81nHb04u6k2N7fPX2bXiiBaV4hw2OGa5GECUUy5yu1n3WpwiwxyV7omcVKFFAA"
  },
  "/assets/products/renders/classic-polo.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSI8AAAABgJtt2/EstW1zBqtNabPmAKmyxDdBjixj23Z+4ynjZIGImAD0a9JN4bCJeYUi3dxsWxn1BWf5bToeT9+qnjPcLMDfcvkHUOCfOL8AYLkEgO/gSXLe3sDnJ2xb8xQWjUbTdeY2AEDPZmShzwoaJ205+iL3nPSFKv////8NySV8BEEQJEG6hEYTCAQC+izq4QBWUDggKAAAANACAJ0BKhAAFAA/KX61Ui4oJSKwCAHAJQlnAACJ9AAA/u96WiMAAAA="
  },
  "/assets/products/renders/crew-neck-tee.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRvIAAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSIoAAAABgFvbtqqK+ODuLj24tOAuBWgBRDTxCmDQA4Ma3J3QyRxO+AT4v4GImAD4qxwOM7ldq3XIGTgadYBa000TG+AmFl3hOEmhaSHi5YKIXR0pdkPae45U2S5OpPN8W+UAgMwTWJDWIb8SKPVT0sIGtBoqyz8avt/v99RMx8sTBEGUhXQAfD6fD5SsnwNWUDggQgAAAHADAJ0BKhAAFAA/KYC2Uq4oJSKwCAHAJQlnAABb1erDVGl4AAD+7n8BKYiFHMX9qdQ0wRpUnixgZAGwr4ud9htgAA=="
  },
  "/assets/products/renders/crewneck-sweatshirt.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRgIBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSLIAAAABgGrbtuommpk0M3MkqUSTyi/ERqaMjltFsoq5mpmZHHPvu0ee90pfEBETwP+vQuH3NJlyOav5hn/qgWEepyMc7jmghFBY9LE1AAClANDONgKcoyKkXOJa0yHDBUMQYa5tKP54/4ge754TKEf2btDtLi2hCkydofNJqKJ+0nWMzjrIAJ/PFzSe1h2x1J22i/l8vr6Q2Hx7e3vbTRdNfFZF/dDw8FCzls8tViqVSjEf8/4cVlA4ICoAAADQAgCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAifQAAP7vL7azAoRPaAA="
  },
  "/assets/products/renders/fleece-jacket.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRhoBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSMIAAAABgKpt//nnn21FzLaXlNZXdxw2kvOvzUa1jQPwkr198XnjD8MRRMQEmP+p3eGwG8oYVJTBLAP5m+cXF+fbpTrpS19XFxdXn6tZWl3A18fHF9CjNQ3ijHHCok3l3QfAOYDjkCrmChCMCcJtkqr4RUISSYi3MlW1uPsUROLzjmpUtTh+Isbo6RitKgUzD+AcD9MYMpvNlsaz7gcuBH/sOmu3m81me2zlEwC8VMV7zJrhkeXl5eWJBLO+NxAIBHxmtenPAVZQOCAyAAAAMAMAnQEqEAAUAD8pfrZSriglIrAIAcAlCWcAAHra82NvAAD+7wbQgwqNKRMtpTAoAAA="
  },
  "/assets/products/renders/long-sleeve-polo.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRg4BAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSLYAAAABgGrbtuommpk8M6vIuPxAbEY0aoaSq+u4qi6jrorZo2NmZm7vlueWfyAiJkD6P43JTCZp/kKovX51vTEQ+yQwfXd8eHh8NxsW9QAf5+cfQK9oEMD5OYAhBdHPAXh+BrBkIda9j3cAeP84dJP47fUtub26T5DU+8oROV7maVLC+A7ZHUOL9INtkp0+tKVSqay6VNwQFJY6lFKpVGn1LXPO+XrQppMKVVnGGCtqpF9UqVQqqVDy61ZQOCAyAAAAUAMAnQEqEAAUAD8pfrVSriglIrAIAcAlCWcAAFvrjbK9osAA/u53W0gaHoe1kMuAcAA="
  },
  "/assets/products/renders/pullover-hoodie.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRggBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSLgAAAABgLJt2/lX9D/bypztRTMr7XMs2ms245Jt23a1976744tji4gJUP6xLS3dLmVseX1ts8okvwBvWRLhcwCwGCMIngR3JoxXBmEtr180oGHMawCllAJbDsZ1QwkAEHrvx8Q/Pz4zzw+vCUw2ObojPz/k/vA3nynA6DkAXIygkGklDSfMWR3pViqVqvLLkhPy80POSy5rtUql0pmbsPv+/v5+mJznUXJNpb19fb2VdqVYazabzVolq/h3VlA4ICoAAACwAgCdASoQABQAPyl+tlIuKCUisAgBwCUJZwAAeyAA/u8tQGXTvB7goAA="
  },
  "/assets/products/renders/safety-vest.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRjIBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSKoAAAABgGMBAOkm80dsG5PWbM6kPS+TbaMee4NOtm27m+12a7f2BHEuEBETADQnGwsAWHYlfXMK6cwQuhz26N9k+Dsnl6Nf/6qUP/e8cuL3WT59/EtWTv/eZjFmP0zlQt9rCwsr34ly1ns5gSC5sZcL33AAgHqRKtf15LXZHA/d5Xrex0dGRt96y80eUNBo/PYSqhRmfwMLAMDyCaFMIQKDIOhrw5cqDwEAACDqDlZQOCBiAAAAMAMAnQEqEAAUAD8pgLpTLigmIrAIAcAlCUAAC31/+JDckAD+7ndvFO3uf8lPOhxkY4jirl25cbRq7NiXuHlDslJ7Afvj1/b0ALN6oXsxuowhonVe7mnekDjhfRfbVTgAAAA="
  },
  "/assets/products/renders/uniform-cap.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSHUAAAABcBvbtqoQu7tD6u4F0IqGXoFb5nU49KAVOGQuJ8WhgIiYAOJ/pLp9fjftCU5ydbutM7xH4RMAnBIPJEPcHavuGWbAFcDCfo/ZBi4XYMC/R0xecAPQtohJd+TxcqM53e7mJcYdIpFG56m9oZyH+CKF+A8JHwcAVlA4ICgAAADQAgCdASoQABQAPyl+tlIuKCUisAgBwCUJZwAAifQAAP7velfF4UAA"
  },
  "/assets/products/renders/uniform-tie.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSIQAAAANcFXbtqoc3N3doQJZKEET7eDQgkEEd/9zl3vfQw+SICImQAp/ygUG545yUj1UOAS9Mkp1ZnUrVMksmEhRc5a3x0lMZLNBaYQsnaOsR0Y+RbkJa+qjggSCLVSIgL/LIqQGAo7NGqEVEDAwc8Rh5oe+UYpYxCL8rPTF4Qmqaa4Y0KRyhddWUDggLgAAADADAJ0BKhAAFAA/KX62Uq4oJSKwCAHAJQlnAACJ3M+NoAAA/u+c1Jdw/Q2cAAA="
  },
  "/assets/products/renders/utility-work-shirt.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRhoBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSLwAAAABgGpb2zJlsrtmN9yJ3MA0Kms6Gt2h0VyaW3Ina3PXNq4f8z7xF+wGImICpP/TEggGA1YRRYs3odDtcplA/kHyIx7/SB4X8Q0BjIgBw3xrIJZKMcK6gqM/ASiTIeDCwrG95BjLZBjLvXs41dFwFESIhuI1nNqvqw8A+LykOk4rdp44z9vo5cxg7B5EeBrBrFQqlXWcN90BwFPjRZ9SKpUq7f4rgHBXYNdJeVX1k5OTky0aqUiVSqWS8kp+HVZQOCA4AAAA8AIAnQEqEAAUAD8pfrVSLiglIrAIAcAlCWdpHwA3WAAA/u7bMe/p3oH+fWn7mg4HjTX90LOHAAA="
  },
  "/assets/products/renders/waist-apron.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRroAAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSGgAAAABcFtr25qkfmO1e8pUngBT6RzQwQ4cBoEZfIdfS1wGiIgJwP83XOuR5ZpAsVqO53fHi3UDaG53lnevI1cHgOxICSGEnnPcTQ/y7hcdKSGE0CfO4u71gbXZ7W+34T1YYRRFUWjhrcrHAVZQOCAsAAAA0AIAnQEqEAAUAD8pgLZSvCglIrAIA4AlCWcAAIn0AAD+7y/6R0B1kuVoAAA="
  },
  "/assets/products/renders/work-jacket.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRiQBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSMUAAAABgKpt//ln+W8jzraVlNZXdxw2kvOvzUa1jQPw0t/+f3/f/+eNPwxHEBEToPmnBqPRoKpsXhDmK1TUnr++vb1eNiuUHiQ+3t4+4scVchNAIhZLAFNymyCRMZGwr5fYbkE8meSER7ck6wPgjHHCd4GkMZRCiigFHmmRdHJPnBPxuIe6JN14DBBjFHjEsETAlg+iCN8mFjQajbb/ZdInci76J15GDRqNxpDdHgCAUEeuVSObvnR4eHi4lqdRtjmdTqddI037cwBWUDggOAAAAJADAJ0BKhAAFAA/KX62Uq4oJSKwCAHAJQlnAABb642nbDaGdQAA/u53XP19S9Q81jBks5yB4xwA"
  },
  "/assets/products/renders/work-short.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSIgAAAABgJpt27KM7O7uJAZwi0RGcHf4OiQOVvD2L+DpX8BlAXeJ7/vdFYcBImICuHvR3mAYhmm4FyXJ3MKiEiWUEtpa1AVlWYrBohnw8gIcLBCcseTigrDn0nnqG+DkEHgwznM9AtMh8OyZ5/0D+j3gPzYv/vb1Vc58fr0n5qmCsahJH4xFjfO2nLNxVlA4IDAAAADQAgCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAifQAAP7vL77r3wEPe1c5S0f8IAA="
  },
  "/assets/products/renders/work-trouser.webp": {
    "width": 1350,
    "height": 1650,
    "blur": "data:image/webp;base64,UklGRgoBAABXRUJQVlA4WAoAAAAQAAAADwAAEwAAQUxQSKsAAAANgFxr2xrlibunAxpw6YwSaIMeOKwpQCtgxdbjmfknox9WQURMgM+/tCxgPv/GxTlwd7kU9CMD4GkU0BRg6JPgmKPGMpjNBdeYtQTeshd8TdXL2NVaIZzGATfSGyFaqIrYtioh6VW1TMzwU8iUqpexGXwJuaJexuTvQqmolgnlq1AoKmKKNyFT1FNC9rnclc5pCEnGETqwr56nff3a3PMntmc3L7qu3y5MDQAAVlA4IDgAAAAQAwCdASoQABQAPymAtVIuKCUisAgBwCUJZwAAidA0t2AA/u8vts46+2Tu4ZLrUrJp31GPqhAAAA=="
  },
  "/assets/products/tshirts/tee-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7lCDCAAA=="
  }
};
