// AUTO-GENERATED by scripts/scan-assets.mjs — do not edit by hand.
// Regenerate with: npm run assets
//
// Records every image currently present under public/assets. Semantic keys in
// data/assets.ts consult this to decide between a real image and a neutral
// missing-asset fallback.

export type ManifestEntry = {
  width: number;
  height: number;
  blur: string | null;
};

export const assetManifest: Record<string, ManifestEntry> = {
  "/assets/case-studies/uniform-apron-program/detail.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAADQAQCdASoQABAABIB0JZwAAvkPFjkeAAD+6+QicmVQ9gDgAAA="
  },
  "/assets/case-studies/uniform-apron-program/fabric.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAACwAQCdASoQABAABIB0JZwAAudflaoQAP7ufyqUnHN4UAAA"
  },
  "/assets/case-studies/uniform-apron-program/product.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQABAABIB0JZwAApQdlEIXIgAA/vN7fPCrKlmnNCD15KNrPjMookK9/OASdhamljAM1fvIpFOZRnUvI5z5btK1IoAAAA=="
  },
  "/assets/development/fabric-swatches.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkABIB0JQBOgBbr1JdwAP7nOb8Lms1Dknv1J1yg56mAcp8eadif0PofvpYVKqa1MxLP8qiN7hiSb84AAA=="
  },
  "/assets/development/measurement.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAAkABIB0JYwCdADa7ASagAD+wHBQ3igJ1Ziu3Y8zvrrxMxux66aBEuGTi9suCwOZbEjNKsf0/vWHwSgAAA=="
  },
  "/assets/development/pattern.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoQAAkABIB0JQBOkCYiSHQiAAD8Nl5QHFuk0tDCvI4oPoDd897gFnK5B+KmS5kQAAA="
  },
  "/assets/development/tech-pack.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoQAAkABIB0JQBdgBU9ymU+gAD+5oOAzHRhSBOmS/QY+MWet18ObsQT+tnsr8OaUFHp0FCr5+BiNPODAAA="
  },
  "/assets/development/trims.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAACQAQCdASoQAAkABIB0JZwAAlE+RMAA/OGB7/PQ6IzkLQR92mjilerjxvLw8jJ8wDzpByJJ6iDOdpeGAdz31zTC/rSNd44AAAA="
  },
  "/assets/export/carton-marking.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAwAgCdASoQABAABIB0JbACdAEfbElMZmOJAAD+6zJ2ceQYUMX0GXOE/SiZvHXWcaBwudoaBvD3hmI+1KeCVX4go7uTLMQAAAA="
  },
  "/assets/export/cartons.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAgCdASoQAAkABIB0JYgCdH8AFXk6kXIAAP7vy55mQjJ+LaAWCsorMrL8TZ/4rkllpAFFPkgAAA=="
  },
  "/assets/export/container-loading.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAkABIB0JZACdADMsXXriAD8jDLEBp9ecR21S5o1kH3hSUQiCpRys5TKFJhSbrnAOycHkqZSmaO0pvYB+JS+4IYAAA=="
  },
  "/assets/export/warehouse.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoQAAkABIB0JZACdAEQz7zowADJcBH6KtwUctMPWcx8uPG04S7NtLwzRfSbsDAA"
  },
  "/assets/fabrics/canvas.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoQABAABIB0JZACdAEN9ZkkPQAA/ufOtDLd6iPryWZY3uWir/7Hl0AA"
  },
  "/assets/fabrics/cotton-pique.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADwAQCdASoQABAABIB0JZwAAud70GQrBQAA/vImMW1u9RCe/6dvqDgA"
  },
  "/assets/fabrics/fleece.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAQCdASoQABAABIB0JQBOgCB/4sdCyBAA/r4BYpkUBiZDIrqkugtjzXhsjOT9EYAAAA=="
  },
  "/assets/fabrics/mesh.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADQAQCdASoQABAABIB0JZwAAuRye3mpAAD+58+RCpIt1W+YIsbOBAAA"
  },
  "/assets/fabrics/polycotton-twill.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQABAABIB0JQBOgCHhT8MhOAD+20G0Qs0YReEazJu2T++iEYZ1gAAA"
  },
  "/assets/fabrics/polyester-performance.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQABAABIB0JaACdAEK6EJlsgD+LLVaDSkTy+DbHFFFH/195Q7FEIAA"
  },
  "/assets/fabrics/rib.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADwAQCdASoQABAABIB0JQBOgCHhm8S+cqAA/uS9nnV9pf1sJX3snejVygAAAA=="
  },
  "/assets/fabrics/single-jersey.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAADQAQCdASoQABAABIB0JZwAApPBx2KQAAD+sxLWjkm17Je4P4docAAA"
  },
  "/assets/fabrics/softshell.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQABAABIB0JaQAAl1/b71F4AD+26Rva+aBQBNw6neSogFyMnNlAAAA"
  },
  "/assets/fabrics/woven.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADwAQCdASoQABAABIB0JQBOgCG+sEpO8AAA/tWBSk+2eB4QS6LQZbapImPRMAAA"
  },
  "/assets/factory/cutting.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoQAAkABIB0JZQAAp2l5vmQAP6muRSHGBVkqP4k14BVnOPCw/LfDOIltoV9kMe+CAAAAA=="
  },
  "/assets/factory/embroidery.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoQAAkABIB0JZwAApOpvSlCt6AA+pGpPqEwC2N+Z4LRx+5ICptG8OrLUe3EARK4wAA="
  },
  "/assets/factory/fabric-inspection.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAkABIB0JYwAAxPH+OyxHYAA/r6CxF8aemJfB4A2duLBs5iNCZX5bo0tYsV42ese8lLjHm2AAA=="
  },
  "/assets/factory/finishing.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkABIB0JZwAAvh5r3m+MAD7IuqH6Syw459YlkEOi1iFcDOlfJLhPCc0iw9guFZny0AchJUIAA=="
  },
  "/assets/factory/packing.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAACwAQCdASoQAAkABIB0JQBOgBLpU7cAAPsiwaac0DN3eM6hKxIaCnViU3E2xliWY/GFkS/RduICBjczqDVhxgAA"
  },
  "/assets/factory/quality-control.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkABIB0JZwAApv1olqAAAD+wSKlRCico/Bbp//Jta5CDYkF9b/HVQ/YQA9sf4EjwXKYLBUAGnKCHxGHAAAA"
  },
  "/assets/factory/sewing.webp": {
    "width": 1600,
    "height": 900,
    "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAkABIB0JYwC7AEO2zCrVIAA9G2FNjNAWk8et60NYa/QRqQr5f8yKqJt3RvMpvNa6Nlw+HBdzy9gAAA="
  },
  "/assets/hero/hero-sewing-01.webp": {
    "width": 1920,
    "height": 1080,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAkABIB0JYwC7AEfUKOKQAD925yORHgZ1oSm4aSiTSGbSXb505d/Y8EdtJlM/ULdmWhKP4uEAA=="
  },
  "/assets/products/aprons/apron-black-front.webp": {
    "width": 1600,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQABAABIB0JZwAAn/8QhOenF4AAP7zgHol7nLbSmFPr5j2jOUPTjQsxu5yHKwMTl/g8RQQ/JRjF2WysgqHhDO1MX+lMVAKAAA="
  },
  "/assets/products/aprons/apron-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAPzEgQAAAA=="
  },
  "/assets/products/fleece/fleece-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7wGCAAAA=="
  },
  "/assets/products/photography/denim-utility-jacket.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoQABQAPyl8tlIuJ6UisAgBwCUJYwDCgCBS7y2BqWC1YTYA/uqW/OHB82+/XROkedE5GbtNKeOXlHJARlKYKBP30EnOPLa5vI3C8RCrwpdEikF5BBkhigxoAAA="
  },
  "/assets/products/photography/henley-green.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABwAwCdASoQABQAPyl+tlKuKCUisAgBwCUJZQAAUYALmTb2sEAA/ufuGMwVuAS5WJRrXWJmPzvvJE8hyDMC1sZ6DOIkae9kHobd3iCNl5yn02CDHqQzRl1BCXnvh116V6L212AA"
  },
  "/assets/products/photography/henley-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZQAAUYBlFx96QWCAAP7n7BZsjv4t+DFO1eepbt3IxFQy/Zd0UsPZXvDi9D0UUbcTbHpy7s3KxB7O8946yuOFpNpWP1DYqAA="
  },
  "/assets/products/photography/henley-tee-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACQAwCdASoQABQAPyl+tlKuKCUisAgBwCUJZQAAUXgvNR4p44MAAP7rJbJWqGiovd5u2uLAOSFjGoHbHYHXMHg1F97dIaHtM1TIPlemEg+2HJS9h+TLO1ZH1Wk6xaiDsAAAAA=="
  },
  "/assets/products/photography/henley-waffle-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoQABQAPyl+tlKuKCUisAgBwCUJYwAAUOVq46REDF9jyAD+6pI/KhsHvJ2r296A4kOotH2X8j2VECoDDVQfS8I+z5K1JuI4TPqRi0QT4oqHnumqp4scAAAA"
  },
  "/assets/products/photography/hoodie-black.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAV7H62PUPIkg0XcAA/uqIWae6lRYEDJF7eEDswwp1cTV05kTZjCm/tXow+DVLS+Gsfv0gf9JC+qcA9bRVKjVmZf+TsO2EKZo4AAA="
  },
  "/assets/products/photography/hoodie-navy-alt.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJYwAAXrV/Avqsen5W8xQAAP7qiEHCpVa1UARiABCxZJUivzTAwYK3c+BvnWCcV+1DykGI2fh5o4ueiVGtAkA/7GLHcBBCJ2YdRkG/4NLSeMuwAAA="
  },
  "/assets/products/photography/hoodie-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQAARmYI2v6ko5uPQAD+6n+8lk0AD0lq5PNK4AcSwiqbDP2L1H0ZsDvkrpubkOi0A9QE2x9II+lqJRFzgnav/E285r3EHyUk/iGRppmLSliAAAA="
  },
  "/assets/products/photography/lounge-pant-grid.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoQABQALumUymUkri4uDgDoSzgABSTci6/N30TAAP7zgnAXXUNn1pwEwCsweE3WhwFoMGKa4AAAAA=="
  },
  "/assets/products/photography/pant-camo.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQCo9B4bYEC2UpsKWAD+598ZG7uaN3v8/W1TQurxtI8DmvsZJAneygHwvkJDy9wf8tOr/08/piOxpYYXnP1Gv1PiWIA7CSuutHswAAA="
  },
  "/assets/products/photography/polo-dress-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoQABQAPyl+tlIuKCUisAgBwCUJZwDG9BI3mcwSJCmiYAD+6pfN8O50wgGUzTKi3UTqeMWYMFdoS0zGo/RDeYtK9VZ3PXtzRcKeROyzfawrLK2llZrXjGZHcB82HODl8K2MwhZgxgAAAA=="
  },
  "/assets/products/photography/polo-green-ribbed.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZQDE2B7BFm9SvIjU2pXAAP7rJbJWqGdYmpzd2KQE9cTlWBP1Yns35TajWK/JcPcBMpNvazWU+GHAWTTMFgjHEKsAAA=="
  },
  "/assets/products/photography/polo-lime.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoQABQAPyl8tlIuJ6UisAgBwCUJbACdACB/0UXXFELoAP7qlaK3spoCsPjuyveQ6F8UAuS3rzrWrJTFDAGRWfoaScJpYwyoKNdEeC9fGYczMupPuPhAAAAA"
  },
  "/assets/products/photography/polo-taupe-long-sleeve.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoQABQAPyl+t1KuKCWisAgBwCUJZQAARj8Co/9ox+AA/uqHYj+UvBTwrK7Jh3D4mSMd3moN9Bp638AjdNipALOtYjL61LyublkJmGU0AAA="
  },
  "/assets/products/photography/polo-yellow.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAwCdASoQABQAPyl+t1IuKCWisAgBwCUJZgCdACHhW31nwq09jrMAAP7qjlCZ1s1BtWw2G2kZ9vyLIlqdkJ1GFKK4AAAA"
  },
  "/assets/products/photography/scarf-camel.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoQABQAPyl+tlIuKCUisAgBwCUJZACw7B97/UuCK8YkSFPgAP7rJY3r6oxkj5VDQSRmcEh46zx2nVDPI0N6z0hypW4BefH/2xwxuL9BkApgZVKkqyEnagAA"
  },
  "/assets/products/photography/scarf-herringbone.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZwAAWnv57gRtJZXxed+AAP7gzfPEUAu1nPYkZTugwNUSxohhmjGEinwmSt9SyjzVXDJILEMzbgzbwHJ2p55NU1HsNBslqznUfhQAAAA="
  },
  "/assets/products/photography/scarf-navy-looped.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQAAXdPPuCJqMajBAAD+15Utoaav7H+BSO45zK9zy43DniMrLX3hCAR05GYzP49xeMoP+usYUDr7ve0A3b6Ns2WteHCHGN9WSwm0aKfAAA=="
  },
  "/assets/products/photography/scarf-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAwBACdASoQABQAPyl+tVIuKCUisAgBwCUJZwAM4AIJN1wbXexzE0PkagAA/uqU05gBegZiVDUUxfCuSTifPjFvY1r/XP/TnxRZYvhmLzRjXCB7w/uvfh0dPXdnmFT0iAIMrpi87TRHQOvyqEecyFNYQlrAxIQA"
  },
  "/assets/products/photography/scarf-plaid-maroon.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZQAAXdGh/3Tei6vDdgAA/tYZTQU6JhA+j0E8aoZUDurXKABnEG/KygXUIjbu07qVWHp2+AwjPCYVr1oEiOvM74jtmrxr/HaYogFrCAA="
  },
  "/assets/products/photography/scarf-plaid-olive.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwDMHCK5mazCOXFD8HgA/sl2nVlb59uOrxHdgbXXc/e5/bNf3xX2Dmkxyjf68wGu4H6xIMOmRqLb4DeVpd88SaGLpk9QPFAAAA=="
  },
  "/assets/products/photography/sweater-red-striped.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJbACsAB4kiWhWFIzuzVrIAP7qlaU0S4iOF8UmMFy83Uxi3IIqxYdFNEDhWjap3CT3XbV7OXei5nkxZl7IpXrQdWl8FBpbxifhDnaAAAA="
  },
  "/assets/products/photography/thermal-sage-alt.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoQABQAPyl8tVIuJ6UisAgBwCUJZwAAW49Pt8cJzvoeQAD+5+4Oe/kbr8S1ITUM1FPjnh0MJ2nMcn4eakJzD/9bfXK6fiJY4AAAAA=="
  },
  "/assets/products/photography/thermal-sage.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoQABQAPymAtlKuKCUisAgBwCUJZwAAUXoTuHCRyGYuMAD+6pV/7x/HXsgPvMndTTU7zBa1/LuoYjtcOIxL95XtNzu41IAAAAA="
  },
  "/assets/products/photography/utility-bomber-charcoal.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoQABQAPyl+uFKuKCWisAgBwCUJZwAAV4RyIoR6ImkHwWQA/uqIQOFIJSp9TtfGZAz5jV3sGqosHj0lFtJuXuxdi1T12KYEYTRepE/HXOu2wQmz+XEAAAAA"
  },
  "/assets/products/photography/work-vest-orange.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAwBACdASoQABQAPyl+tVIuKCUisAgBwCUJbACdMoLUABOuyOUmxt4wAuQA/ufsS9C+V3xFB/zYMu7LGHBDnKdpchmgNoc4T4rxZH7bqXbTJQGXh4wYHJlkJuf6TEcQRayanqxzJ3TumEeqNAnkKoqZkJ4ON6swnAAAAA=="
  },
  "/assets/products/photography/zip-hoodie-grey.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoQABQAPymAtlKuKCUisAgBwCUJZwAAUrmB5XgTf+DOAAD+6pbmvXiFIkyM+1LC6r2LvQ1HgvcReYbiktEAQAAA"
  },
  "/assets/products/photography/zip-hoodie-navy.webp": {
    "width": 1280,
    "height": 1600,
    "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoQABQAPyl+tVIuKCUisAgBwCUJZQAAV7H7/YLTu3rFoAD+6pLFDLYUt6YcJ9SOTTkGWqjqS/GcnXXIQRbN/I1fjGy3MohacRs/ik+NJYXw6F+Y/9pZTGKJ8A6A5XO04c0IAA=="
  },
  "/assets/products/polos/polo-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7vTEAAAA=="
  },
  "/assets/products/tshirts/tee-fabric-macro.webp": {
    "width": 1200,
    "height": 1200,
    "blur": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAABQAQCdASoQABAABIB0JaQABDOAAP7lCDCAAA=="
  },
  "/assets/texture/weave.webp": {
    "width": 500,
    "height": 500,
    "blur": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAABQAQCdASoQABAABIB0JaQABHQAAORAAAA="
  }
};
