// AUTO-GENERATED by scripts/content-dates.mjs — do not edit by hand.
// Regenerate with: npm run dates
//
// When each group of routes last genuinely changed, from git commit dates where
// available. The sitemap reads this so `lastModified` reflects content changes
// rather than deploy time — a date that moves on every build teaches crawlers to
// ignore it.

export const contentDates: Record<string, string> = {
  "home": "2026-08-23T18:04:39.360Z",
  "products": "2026-08-23T18:04:39.360Z",
  "productCategory": "2026-08-24T06:17:55.673Z",
  "manufacturing": "2026-08-21T11:49:24.176Z",
  "manufacturingStage": "2026-08-24T06:19:18.513Z",
  "industries": "2026-08-21T12:02:23.014Z",
  "industry": "2026-08-24T06:19:18.514Z",
  "sourcing": "2026-08-21T11:50:28.194Z",
  "sourcingPillar": "2026-08-24T06:19:18.513Z",
  "resources": "2026-08-21T12:00:01.764Z",
  "guide": "2026-08-24T06:19:18.513Z",
  "caseStudies": "2026-08-21T11:58:42.369Z",
  "caseStudy": "2026-08-21T11:58:42.379Z",
  "about": "2026-08-24T06:28:44.543Z",
  "capabilities": "2026-08-24T06:28:44.543Z",
  "contact": "2026-08-24T06:28:44.543Z",
  "export": "2026-08-24T06:28:44.543Z",
  "materials": "2026-08-24T06:28:44.543Z",
  "product-development": "2026-08-24T06:28:44.543Z",
  "quality": "2026-08-24T06:28:44.543Z",
  "request-a-quote": "2026-08-24T06:28:44.543Z",
  "send-tech-pack": "2026-08-24T06:28:44.543Z",
  "sustainability": "2026-08-24T06:28:44.543Z",
  "privacy": "2026-08-24T06:29:18.107Z",
  "terms": "2026-08-24T06:29:18.109Z",
  "cookies": "2026-08-24T06:29:18.111Z"
};
