#!/usr/bin/env node
/**
 * Regenerates assets-needed.md — the shot list.
 *
 *   npm run assets:report
 *
 * Two things changed about how this counts, and both mattered.
 *
 * It used to read `data/assets.ts` as text and pull keys out with a regular
 * expression. That silently disagreed with the site: it reported 27 slots
 * "awaiting photography" when `assetCoverage()` — the function the components
 * actually use — reported 12 missing files and zero visible gaps. Handing a
 * photographer a list with fifteen shots on it that nobody needs is worse than
 * handing them nothing. The registry is now imported through the same
 * type-stripping loader the tests use, so this file and the site cannot
 * disagree by construction.
 *
 * And "missing" was one bucket doing two jobs. A key with no file and no
 * fallback leaves a hole on the page. A key whose canonical shot is missing but
 * whose fallback renders shows a stand-in — a garment render where a factory
 * floor was intended, say. The second is not broken, but it is the single
 * biggest quality gap on the site, and it is invisible to a count that lumps
 * the two together. They are separated below, and the stand-in list names what
 * is showing instead so the value of each shot is legible.
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const { assetRegistry, resolveAsset } = await import("../data/assets.ts");
const { assetManifest } = await import("../data/asset-manifest.ts");

/** Where a key is asked for, so a shot can be traced to the page it fixes. */
function referencedBy(key) {
  try {
    const out = execFileSync(
      "grep",
      ["-rl", "--include=*.tsx", "--include=*.ts", `"${key}"`, "app", "components", "data"],
      { cwd: root, encoding: "utf8" },
    );
    return out
      .split("\n")
      .filter(Boolean)
      .filter((f) => !f.startsWith("data/assets.ts") && !f.startsWith("data/asset-manifest.ts"));
  } catch {
    return [];
  }
}

const ORIENTATION = {
  hero: "3840 × 2160 (16:9 landscape)",
  products: "3000 × 3000 (1:1 square)",
  industries: "2160 × 2880 (3:4 portrait)",
  factory: "3840 × 2160 (16:9 landscape)",
  development: "3840 × 2160 (16:9 landscape)",
  fabrics: "3000 × 3000 (1:1 square)",
  export: "3840 × 2160 (16:9 landscape)",
  "case-studies": "mixed — see manifest",
  brand: "SVG vector",
};

const keys = Object.keys(assetRegistry);
const rows = keys.map((key) => {
  const asset = assetRegistry[key];
  const resolved = resolveAsset(key);
  const canonicalPresent = Boolean(assetManifest[asset.src]?.width);
  const standingIn = !canonicalPresent && resolved.available ? resolved.src : null;
  return {
    key,
    src: asset.src,
    alt: asset.alt,
    canonicalPresent,
    standingIn,
    gap: !resolved.available,
    used: referencedBy(key),
    category: asset.src.split("/")[2] ?? "misc",
  };
});

const complete = rows.filter((r) => r.canonicalPresent);
const standIns = rows.filter((r) => r.standingIn);
const gaps = rows.filter((r) => r.gap);
const wanted = [...gaps, ...standIns];

/* Rendered shots first: a slot no component asks for is not worth a day out. */
const rank = (r) => (r.gap ? 0 : 1) * 100 - r.used.length;
wanted.sort((a, b) => rank(a) - rank(b));

let out = `# Shot list

**Generated by \`npm run assets:report\` — do not edit by hand.**

Counted through \`resolveAsset()\`, the same path the components use, so this
cannot disagree with what the site renders.

## Status

| | Count |
|---|---|
| Slots defined | ${keys.length} |
| Canonical file in place | ${complete.length} |
| Showing a stand-in | ${standIns.length} |
| **Leaving a visible gap** | **${gaps.length}** |

${
  gaps.length === 0
    ? "No slot is empty on the page. Every shot below replaces a stand-in with the\nthing it was meant to be — which is a quality problem, not a broken one."
    : "Slots below marked **GAP** render nothing. Shoot those first."
}

## How to add a shot

1. Export the master to \`assets-master/\` mirroring the path below.
2. \`npm run images:build\` cuts the web derivative at the right size and quality.
3. \`npm run assets\` reindexes and generates the blur placeholder.
4. \`npm run images:audit\` gates it on byte budget.

No component or layout change is needed at any point.

## Two rules that override everything

- **No logos, brand marks or identifiable organisations** in any image.
- **No image may present a concept visual as documentary proof** of a facility,
  a certification or a shipment.

`;

if (wanted.length) {
  out += `## Wanted, most valuable first\n\n`;
  out += `Ranked by whether the slot is empty, then by how many pages ask for it.\n\n`;
  for (const r of wanted) {
    out += `### ${r.key}${r.gap ? " — **GAP**" : ""}\n\n`;
    out += `- **Path:** \`${r.src}\`\n`;
    out += `- **Master size:** ${ORIENTATION[r.category] ?? "see manifest"}\n`;
    out += `- **Subject:** ${r.alt || "—"}\n`;
    if (r.standingIn) out += `- **Currently showing:** \`${r.standingIn}\`\n`;
    out += `- **Used by:** ${r.used.length ? r.used.map((f) => `\`${f}\``).join(", ") : "no component yet"}\n\n`;
  }
}

out += `## In place\n\n${complete.length} canonical files.\n\n`;
for (const r of complete.sort((a, b) => a.src.localeCompare(b.src))) {
  const d = assetManifest[r.src];
  out += `- \`${r.src}\`${d?.width ? ` — ${d.width}×${d.height}` : ""}\n`;
}

fs.writeFileSync(path.join(root, "assets-needed.md"), out);
console.log(
  `assets-needed.md written — ${complete.length} in place, ${standIns.length} showing a stand-in, ${gaps.length} leaving a gap`,
);
