#!/usr/bin/env node
/**
 * Regenerates assets-needed.md from the live asset registry.
 *
 * The checklist is generated rather than hand-written so it cannot drift out of
 * sync: every pending slot listed here is a key whose canonical image file
 * still needs to be supplied.
 *
 *   npm run assets:report
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// The registry is TypeScript; read it as text and extract what we need rather
// than adding a build step to this script.
const src = fs.readFileSync(path.join(root, "data", "assets.ts"), "utf8");
const manifestSrc = fs.readFileSync(path.join(root, "data", "asset-manifest.ts"), "utf8");
// The type declaration also contains braces; start from the record literal.
const marker = "assetManifest: Record<string, ManifestEntry> = ";
const manifest = JSON.parse(
  manifestSrc.slice(manifestSrc.indexOf(marker) + marker.length, manifestSrc.lastIndexOf("}") + 1),
);

const entries = [];
const blockRe = /"([\w.]+)":\s*\{([^}]*?)\}/gs;
let m;
while ((m = blockRe.exec(src))) {
  const [, key, body] = m;
  const src_ = body.match(/src:\s*"([^"]+)"/)?.[1];
  const alt = body.match(/alt:\s*"([^"]+)"/)?.[1];
  const kind = body.match(/kind:\s*"([^"]+)"/)?.[1];
  if (src_) entries.push({ key, src: src_, alt, kind });
}

// The render() helper generates its own entries; add them from the public dir.
const renderDir = path.join(root, "public", "assets", "products", "renders");
if (fs.existsSync(renderDir)) {
  for (const file of fs.readdirSync(renderDir)) {
    const p = `/assets/products/renders/${file}`;
    if (!entries.some((e) => e.src === p)) {
      entries.push({ key: `renders.${file.replace(/\.\w+$/, "")}`, src: p, kind: "garment" });
    }
  }
}

const present = entries.filter((e) => manifest[e.src]);
const missing = entries.filter((e) => !manifest[e.src]);

const byCategory = new Map();
for (const e of missing) {
  const category = e.src.split("/")[2] ?? "other";
  const list = byCategory.get(category) ?? [];
  list.push(e);
  byCategory.set(category, list);
}

const ORIENTATION = {
  hero: "3840 × 2160 (16:9 landscape)",
  products: "3000 × 3000 (1:1 square)",
  industries: "2160 × 2880 (3:4 portrait)",
  factory: "3840 × 2160 (16:9 landscape)",
  development: "3840 × 2160 (16:9 landscape)",
  fabrics: "3000 × 3000 (1:1 square)",
  export: "3840 × 2160 (16:9 landscape)",
  "case-studies": "mixed — see manifest",
  brand: "SVG vector",
};

let out = `# Assets Needed

**Generated by \`npm run assets:report\` — do not edit by hand.**

The site keeps its layout stable if a future asset is absent. The current visual
library covers every registered image surface, so this report should be empty
after the supplied asset pack is indexed.

## How to add an asset

1. Export the final file to the exact path listed below.
2. Run \`npm run assets\` to reindex and generate its blur placeholder.
3. Rebuild. No component or layout change is required.

## Status

| | Count |
|---|---|
| Slots defined | ${entries.length} |
| Files present | ${present.length} |
| Awaiting photography | ${missing.length} |

## Photography direction

Master prompts for every slot are in \`asset-pack/prompts/\`, and the shared
photography language is in \`asset-pack/docs/4K_PHOTOGRAPHY_STANDARD.md\`.

Two rules override everything else:

- **No logos, brand marks or identifiable organisations** in any image. The
  industry photography shows the *kind* of environment a program serves; it must
  never imply that anyone shown is a customer.
- **No image may present a concept visual as documentary proof** of a facility,
  certification, capacity or client relationship.

`;

for (const [category, list] of [...byCategory].sort()) {
  out += `\n### ${category}\n\n`;
  out += `Master size: ${ORIENTATION[category] ?? "see manifest"}\n\n`;
  out += `| Path | Semantic key | Subject |\n|---|---|---|\n`;
  for (const e of list.sort((a, b) => a.src.localeCompare(b.src))) {
    out += `| \`${e.src}\` | \`${e.key}\` | ${e.alt ?? "—"} |\n`;
  }
}

out += `\n## Already supplied\n\n`;
out += `${present.length} files are in place, including ${present.filter((e) => e.src.includes("/renders/")).length} representative product renders.\n\n`;
out += `| Path | Dimensions |\n|---|---|\n`;
for (const e of present.sort((a, b) => a.src.localeCompare(b.src))) {
  const d = manifest[e.src];
  out += `| \`${e.src}\` | ${d.width} × ${d.height} |\n`;
}

fs.writeFileSync(path.join(root, "assets-needed.md"), out);
console.log(`assets-needed.md written — ${present.length} present, ${missing.length} pending`);
