#!/usr/bin/env node
/**
 * Image audit.
 *
 *   npm run images:audit
 *
 * Inspects every file served from `public/assets`, checks it against the role
 * budgets in `data/image-spec.ts`, cross-references the semantic registry, and
 * writes `reports/image-audit.json`.
 *
 * Each finding is PASS, WARNING or FAIL:
 *   FAIL     — will hurt users: over the hard byte ceiling, a master shipped by
 *              mistake, a broken registry path, an unsupported format.
 *   WARNING  — worth looking at: over its role budget, suspiciously small
 *              (over-compressed), an odd aspect ratio, a duplicate.
 *   PASS     — within budget and correctly shaped.
 *
 * Exits non-zero on any FAIL so it can gate a deploy.
 */

import { execFileSync } from "node:child_process";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const WEB = path.join(root, "public", "assets");
const REPORTS = path.join(root, "reports");

const KB = 1024;
const SPEC = {
  hero: { w: 1920, h: 1080, max: 350 * KB, min: 60 * KB },
  productSquare: { w: 1600, h: 1600, max: 220 * KB, min: 12 * KB },
  productRender: { w: 1350, h: 1650, max: 220 * KB, min: 12 * KB },
  productThumb: { w: 800, h: 800, max: 100 * KB, min: 6 * KB },
  modelPortrait: { w: 1200, h: 1600, max: 250 * KB, min: 30 * KB },
  technicalDetail: { w: 1400, h: 933, max: 180 * KB, min: 8 * KB },
  fabricMacro: { w: 1200, h: 1200, max: 200 * KB, min: 12 * KB },
  industry: { w: 1600, h: 900, max: 250 * KB, min: 20 * KB },
  social: { w: 1200, h: 630, max: 250 * KB, min: 12 * KB },
};

const ABSOLUTE_MAX = 500 * KB;
const MASTER_WIDTH = 2400;
const ALLOWED = new Set([".webp", ".avif", ".jpg", ".jpeg", ".png", ".svg"]);

/**
 * Roles where an unusually small file really does indicate over-compression.
 * Flat textures, cut-out renders and technical diagrams have little entropy and
 * compress to a few KB at full quality — flagging those is a false positive.
 */
const PHOTOGRAPHIC = new Set(["hero", "modelPortrait", "industry"]);

function roleFor(rel) {
  if (rel.includes("/hero/")) return "hero";
  if (rel.includes("/renders/")) return "productRender";
  if (rel.includes("/industries/")) return "modelPortrait";
  if (rel.includes("/factory/") || rel.includes("/export/") || rel.includes("/development/")) return "industry";
  if (rel.includes("/fabrics/") || rel.includes("fabric-macro")) return "fabricMacro";
  if (rel.includes("/details/") || rel.includes("-detail")) return "technicalDetail";
  return "productSquare";
}

function dimensions(file) {
  try {
    const out = execFileSync("ffprobe", ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height", "-of", "csv=p=0:s=x", file], { encoding: "utf8" }).trim();
    const [w, h] = out.split("x").map(Number);
    return Number.isFinite(w) && Number.isFinite(h) ? { width: w, height: h } : null;
  } catch {
    return null;
  }
}

function walk(dir) {
  const out = [];
  if (!fs.existsSync(dir)) return out;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

/* -------------------- registry cross-reference -------------------- */

const registrySrc = fs.readFileSync(path.join(root, "data", "assets.ts"), "utf8");
const declaredPaths = new Set([...registrySrc.matchAll(/(?:src|fallbackSrc):\s*"(\/assets\/[^"]+)"/g)].map((m) => m[1]));
// Renders are generated by a helper rather than written out one by one.
for (const m of registrySrc.matchAll(/render\("([\w-]+)"/g)) declaredPaths.add(`/assets/products/renders/${m[1]}.webp`);
const missingAlt = [...registrySrc.matchAll(/"([\w.]+)":\s*\{[^}]*?src:\s*"(\/assets\/[^"]+)"[^}]*?\}/gs)]
  .filter(([block]) => !/alt:\s*"/.test(block))
  .map(([, key]) => key);

/* ------------------------------ audit ------------------------------ */

const findings = [];
const hashes = new Map();
let pass = 0, warn = 0, fail = 0;

const add = (status, file, check, message, extra = {}) => {
  findings.push({ status, file, check, message, ...extra });
  if (status === "FAIL") fail++;
  else if (status === "WARNING") warn++;
  else pass++;
};

const files = walk(WEB).filter((f) => !f.endsWith(".PLACEHOLDER.txt") && !f.endsWith(".md"));

for (const file of files) {
  const rel = "/" + path.relative(path.join(root, "public"), file).split(path.sep).join("/");
  const ext = path.extname(file).toLowerCase();
  const bytes = fs.statSync(file).size;

  if (!ALLOWED.has(ext)) {
    add("FAIL", rel, "format", `Unsupported format "${ext}" in the served asset tree.`);
    continue;
  }
  if (ext === ".svg") {
    add("PASS", rel, "format", "Vector asset.", { bytes });
    continue;
  }

  const role = roleFor(rel);
  const spec = SPEC[role];
  const dim = dimensions(file);

  // Duplicates: identical bytes served from two paths.
  const hash = crypto.createHash("sha1").update(fs.readFileSync(file)).digest("hex");
  if (hashes.has(hash)) {
    add("WARNING", rel, "duplicate", `Byte-identical to ${hashes.get(hash)}. Serve one and reference it twice.`, { bytes });
  } else {
    hashes.set(hash, rel);
  }

  if (bytes > ABSOLUTE_MAX) {
    add("FAIL", rel, "filesize", `${(bytes / KB).toFixed(0)} KB exceeds the ${ABSOLUTE_MAX / KB} KB hard ceiling for served assets.`, { bytes, role });
  } else if (bytes > spec.max) {
    add("WARNING", rel, "filesize", `${(bytes / KB).toFixed(0)} KB is over the ${(spec.max / KB).toFixed(0)} KB budget for ${role}.`, { bytes, role });
  } else if (bytes < spec.min && PHOTOGRAPHIC.has(role)) {
    add("WARNING", rel, "filesize", `${(bytes / KB).toFixed(0)} KB is below ${(spec.min / KB).toFixed(0)} KB for ${role} — check it is not over-compressed.`, { bytes, role });
  } else {
    add("PASS", rel, "filesize", `${(bytes / KB).toFixed(0)} KB, within the ${role} budget.`, { bytes, role });
  }

  if (!dim) {
    add("WARNING", rel, "dimensions", "Could not read dimensions.", { bytes });
    continue;
  }

  if (dim.width > MASTER_WIDTH) {
    add("FAIL", rel, "master-in-web", `${dim.width}px wide — this looks like an unoptimised master. Move it to assets-master/ and rebuild.`, { ...dim, role });
  }

  // Aspect ratio is checked against the nearest standard shape rather than the
  // one guessed from the folder. A square export macro is correctly shaped even
  // though it lives under /export/; what matters is that it is not a stretched
  // or arbitrary ratio.
  const actual = dim.width / dim.height;
  const STANDARD = { "1:1": 1, "4:5": 0.8, "3:4": 0.75, "9:11": 0.818, "4:3": 1.333, "3:2": 1.5, "16:10": 1.6, "16:9": 1.778, "1.91:1": 1.91 };
  let best = null;
  for (const [name, ratio] of Object.entries(STANDARD)) {
    const drift = Math.abs(actual - ratio) / ratio;
    if (!best || drift < best.drift) best = { name, drift };
  }
  if (best.drift > 0.04) {
    add("WARNING", rel, "aspect-ratio", `Ratio ${actual.toFixed(3)}:1 is ${(best.drift * 100).toFixed(0)}% off the nearest standard shape (${best.name}). Confirm the crop is intentional and nothing is stretched.`, { ...dim, role });
  } else {
    add("PASS", rel, "aspect-ratio", `${dim.width}x${dim.height} is a clean ${best.name}.`, { ...dim, role });
  }

  if (!declaredPaths.has(rel)) {
    add("WARNING", rel, "orphan", "Present on disk but not referenced by data/assets.ts — it ships but nothing renders it.", { bytes });
  }
}

/* Registry paths with no file behind them are expected (photography pending),
   so they are reported as information rather than as a problem. */
const onDisk = new Set(files.map((f) => "/" + path.relative(path.join(root, "public"), f).split(path.sep).join("/")));
const pending = [...declaredPaths].filter((p) => !onDisk.has(p)).sort();

for (const key of missingAlt) {
  add("FAIL", key, "alt-text", "Registry entry has no alt text.");
}

/* ------------------------------ report ----------------------------- */

const totalBytes = files.reduce((sum, f) => sum + fs.statSync(f).size, 0);

const report = {
  generatedAt: new Date().toISOString(),
  summary: {
    filesAudited: files.length,
    totalBytes,
    totalMB: Number((totalBytes / 1024 / 1024).toFixed(2)),
    pass,
    warning: warn,
    fail,
    verdict: fail > 0 ? "FAIL" : warn > 0 ? "WARNING" : "PASS",
  },
  budgets: Object.fromEntries(Object.entries(SPEC).map(([k, v]) => [k, { width: v.w, height: v.h, maxKB: v.max / KB }])),
  pendingPhotography: { count: pending.length, paths: pending },
  findings: findings.sort((a, b) => ({ FAIL: 0, WARNING: 1, PASS: 2 })[a.status] - ({ FAIL: 0, WARNING: 1, PASS: 2 })[b.status]),
};

fs.mkdirSync(REPORTS, { recursive: true });
fs.writeFileSync(path.join(REPORTS, "image-audit.json"), JSON.stringify(report, null, 2));

console.log(`\nImage audit — ${report.summary.verdict}`);
console.log(`  files:    ${files.length}`);
console.log(`  payload:  ${report.summary.totalMB} MB served`);
console.log(`  pass:     ${pass}`);
console.log(`  warning:  ${warn}`);
console.log(`  fail:     ${fail}`);
console.log(`  pending photography: ${pending.length} declared paths with no file yet`);

const notable = findings.filter((f) => f.status !== "PASS").slice(0, 12);
if (notable.length) {
  console.log("\nNotable:");
  for (const f of notable) console.log(`  [${f.status}] ${f.check}  ${f.file}\n         ${f.message}`);
}
console.log(`\nreports/image-audit.json written`);

process.exit(fail > 0 ? 1 : 0);
