#!/usr/bin/env node
/**
 * Records when each route's content last actually changed.
 *
 *   npm run dates
 *
 * Writes `data/content-dates.ts` from the modification times of the source files
 * behind each page. The sitemap reads that constant instead of touching the
 * filesystem at request time — which keeps `lastModified` honest (it moves only
 * when content moves, not on every deploy) without dynamic fs access in the
 * server bundle.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Prefer the git commit date: mtime changes on checkout, commit date does not. */
function gitDate(file) {
  try {
    const out = execFileSync("git", ["log", "-1", "--format=%cI", "--", file], {
      cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return out || null;
  } catch {
    return null;
  }
}

function fileDate(file) {
  const full = path.join(root, file);
  if (!fs.existsSync(full)) return null;
  return gitDate(file) ?? new Date(fs.statSync(full).mtimeMs).toISOString();
}

function newest(files) {
  let best = null;
  for (const f of files) {
    const d = fileDate(f);
    if (d && (!best || d > best)) best = d;
  }
  return best;
}

const GROUPS = {
  home: ["app/page.tsx", "data/products.ts", "data/capabilities.ts", "data/process.ts", "data/materials.ts"],
  products: ["app/products/page.tsx", "data/products.ts"],
  productCategory: ["app/products/[slug]/page.tsx", "data/products.ts", "data/product-faqs.ts"],
  manufacturing: ["app/manufacturing/page.tsx", "data/manufacturing.ts"],
  manufacturingStage: ["app/manufacturing/[slug]/page.tsx", "data/manufacturing.ts"],
  industries: ["app/industries/page.tsx", "data/industries.ts", "data/industry-detail.ts"],
  industry: ["app/industries/[slug]/page.tsx", "data/industry-detail.ts"],
  sourcing: ["app/sourcing/page.tsx", "data/sourcing.ts"],
  sourcingPillar: ["app/sourcing/[slug]/page.tsx", "data/sourcing.ts"],
  resources: ["app/resources/page.tsx", "data/guides.ts"],
  guide: ["app/resources/[slug]/page.tsx", "data/guides.ts", "data/editorial.ts"],
  caseStudies: ["app/case-studies/page.tsx", "data/caseStudies.ts"],
  caseStudy: ["app/case-studies/[slug]/page.tsx", "data/caseStudies.ts"],
};

const dates = {};
for (const [key, files] of Object.entries(GROUPS)) {
  dates[key] = newest([...files, "data/company.ts"]) ?? new Date().toISOString();
}
// Simple routes: their own page file.
for (const route of ["about", "capabilities", "contact", "export", "materials", "product-development", "quality", "request-a-quote", "send-tech-pack", "sustainability", "privacy", "terms", "cookies"]) {
  dates[route] = newest([`app/${route}/page.tsx`, "data/legal.ts", "data/company.ts"]) ?? new Date().toISOString();
}

const out = `// AUTO-GENERATED by scripts/content-dates.mjs — do not edit by hand.
// Regenerate with: npm run dates
//
// When each group of routes last genuinely changed, from git commit dates where
// available. The sitemap reads this so \`lastModified\` reflects content changes
// rather than deploy time — a date that moves on every build teaches crawlers to
// ignore it.

export const contentDates: Record<string, string> = ${JSON.stringify(dates, null, 2)};
`;

fs.writeFileSync(path.join(root, "data", "content-dates.ts"), out);
console.log(`content dates: ${Object.keys(dates).length} groups -> data/content-dates.ts`);
