#!/usr/bin/env node
/**
 * Writes `image-brief.md` — every image the site is still missing, phrased as
 * generation prompts.
 *
 *   npm run brief
 *
 * Derived from the registry through `hasCanonicalAsset`, so a slot appears here
 * only when its own file is absent. A key with a fallback still counts as
 * missing: the fallback is why the page is not broken, not a reason to stop
 * wanting the real thing.
 *
 * Three groups, because they are three different jobs:
 *
 *   1. Article photographs — the garment a product page names. Highest value:
 *      these are what a buyer looks at when deciding whether AHM makes their
 *      product.
 *   2. Sample-strip slots — the "Photographed from production" galleries. These
 *      went quiet when the customer-branded set was withdrawn.
 *   3. Everything else — factory, industry environments, development, hero.
 *
 * The rules block at the top is not decoration. Every image on this site is
 * governed by it, and an image that breaks it cannot be published however good
 * it looks.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const { assetRegistry, hasCanonicalAsset } = await import("../data/assets.ts");
const { productCategories } = await import("../data/products.ts");

const articles = [];
for (const c of productCategories) {
  for (const art of c.articles) {
    if (hasCanonicalAsset(art.asset)) continue;
    // Several articles can share one key, so one image serves all of them.
    // Listing it once per article would have someone generate the same file
    // twice and overwrite the first.
    const seen = articles.find((a) => a.src === assetRegistry[art.asset].src);
    if (seen) {
      seen.alsoUsedBy.push(`${art.name} (${c.name})`);
      continue;
    }
    articles.push({
      family: c.name,
      name: art.name,
      note: art.note ?? "",
      src: assetRegistry[art.asset].src,
      alsoUsedBy: [],
    });
  }
}

const strip = [];
for (const c of productCategories) {
  for (const key of c.photography ?? []) {
    if (hasCanonicalAsset(key)) continue;
    strip.push({ family: c.name, src: assetRegistry[key].src, alt: assetRegistry[key].alt });
  }
}

const other = [];
for (const key of Object.keys(assetRegistry)) {
  if (hasCanonicalAsset(key)) continue;
  const src = assetRegistry[key].src;
  if (src.includes("/products/photography/")) continue;
  other.push({ key, src, alt: assetRegistry[key].alt });
}

/** Where a master must be dropped for `npm run photos` / `images:build` to pick it up. */
const master = (src) =>
  src.includes("/products/photography/")
    ? `assets-master/product-photography/${path.basename(src, ".webp")}.png`
    : `assets-master${src.replace("/assets", "")}`.replace(/\.webp$/, ".png");

/**
 * The subject, with any description of branding removed.
 *
 * These alts were written for the withdrawn originals, so several describe the
 * mark itself — "with printed graphic", "with embroidered logo". Feeding that
 * to a generator alongside "no logo, no text" produces a contradictory prompt,
 * and the generator resolves it by guessing.
 */
function plainSubject(alt) {
  return alt
    .replace(/\.\s*Photographed production sample\.?$/i, "")
    // Any "with ... <mark noun> ..." clause, up to a comma or the end. The
    // adjective is not adjacent to the noun in every alt — "with embroidered
    // chest logo", "with gold embroidery" — so an adjacent-word pattern leaks.
    .replace(
      /,?\s+with\b[^,.]*?\b(logos?|graphics?|text|embroider\w*|prints?|labels?|tags?|badges?|branding|crest|monogram|wordmark)\b[^,.]*/gi,
      "",
    )
    .replace(/\s{2,}/g, " ")
    .trim();
}

/**
 * The article note, kept only when it describes the garment.
 *
 * `note` carries construction detail for most articles and a commercial or
 * compliance statement for a few — the infant bodysuits read "children's safety
 * requirements are qualified against the destination market's standard before
 * development", which is true, important, and not a thing anyone can draw.
 * Feeding it to an image model gives it something to interpret visually, and it
 * will oblige.
 */
function visualNote(note) {
  if (!note) return "";
  if (/qualif|standard|requirement|market|complian|certif|develop/i.test(note)) return "";
  return `, ${note.toLowerCase().replace(/\.$/, "")}`;
}

/** "a" before a consonant, "an" before a vowel. */
const article = (word) => (/^[aeiou]/i.test(word) ? "an" : "a");

const total = articles.length + strip.length + other.length;

let out = `# Image brief

**Generated by \`npm run brief\` — do not edit by hand.**

${total} images are missing. Every one is derived from the asset registry, so a
slot listed here has no file of its own. Some currently show a stand-in, which
is why no page looks broken; the stand-in is not the thing.

## Rules that apply to every image

These are not style preferences. An image breaking any of them cannot go on the
site, however good it looks.

1. **No logos, brand marks, licensed graphics or brand hangtags.** Not on the
   garment, not on a tag, not in the background. 35 photographs were withdrawn
   from this site for exactly this.
2. **No identifiable person and no identifiable organisation.** Environment
   shots show the kind of place a program serves, never a named one.
3. **Nothing that could be read as documentary proof** of a facility, a
   certification, a machine count or a shipment. These are representative
   articles, and the site labels them as such.
4. **Plain white or very light neutral ground**, flat lay or on an invisible
   form, garment square to frame, soft even light, no heavy shadow, no props.
5. **The garment fills the frame** with a small even margin. No lifestyle
   scene, no model, no folded stacks.

## How to use the result

Save each file at the **master path** given, then:

\`\`\`bash
npm run photos          # cuts web derivatives for product photography
npm run images:build    # cuts everything else
npm run assets          # reindex and generate blur placeholders
npm run images:gaps     # must still report 0
\`\`\`

---

## 1. Article photographs — ${articles.length} images

The garment each product page names. Highest value: this is what a buyer looks
at when deciding whether you make their product.

`;

for (const a of articles) {
  out += `### ${a.name}\n\n`;
  out += `- **Family:** ${a.family}\n`;
  if (a.alsoUsedBy.length) out += `- **Also used for:** ${a.alsoUsedBy.join(", ")}\n`;
  out += `- **Save as:** \`${master(a.src)}\`\n`;
  out += `- **Prompt:** Product photograph of ${article(a.name)} ${a.name.toLowerCase()}${visualNote(a.note)}. Flat lay on a plain white background, garment square to frame, soft even studio light, no shadow, no props, no model. **No logo, no brand mark, no printed graphic, no hangtag, no visible text of any kind.** Square 1:1, 3000 x 3000.\n\n`;
}

out += `---\n\n## 2. Production-sample slots — ${strip.length} images\n\nThese fill the "Photographed from production" galleries, which went quiet on\nmost family pages when the customer-branded set was withdrawn. Same rules,\nsame square format.\n\n`;

const byFamily = new Map();
for (const s of strip) {
  if (!byFamily.has(s.family)) byFamily.set(s.family, []);
  byFamily.get(s.family).push(s);
}
for (const [family, items] of byFamily) {
  out += `### ${family} — ${items.length}\n\n`;
  for (const s of items) {
    out += `- \`${master(s.src)}\` — ${plainSubject(s.alt)}. Plain white ground, flat lay, **no logo or text**. 3000 x 3000.\n`;
  }
  out += `\n`;
}

out += `---\n\n## 3. Everything else — ${other.length} images\n\nFactory, environment, development and hero slots. These are scenes rather than\ngarments, so they are landscape and must show no identifiable person, company\nor signage.\n\n`;

for (const o of other) {
  const portrait = o.src.includes("/industries/");
  out += `- \`${master(o.src)}\` — ${o.alt}. ${portrait ? "Portrait 3:4, 2160 x 2880." : "Landscape 16:9, 3840 x 2160."} No identifiable person, no company name, no signage, no brand mark.\n`;
}

out += `\n---\n\n**A caution on generated imagery.** Anything produced this way is an\nillustration, not evidence. It may stand in for an article type, and it must\nnever be presented as a photograph of a real facility, a real shipment or a\nreal production run. Where this site shows a render it says so, and generated\nenvironment shots carry the same obligation.\n`;


/* ------------------------------------------------------------------ *
 * Plain-text companion: image-prompts.txt
 *
 * The markdown is for reading. This is for pasting into an image
 * generator, so it carries no headings, no bold and no code fences —
 * those arrive as literal characters in a prompt and the model treats
 * them as part of the instruction.
 *
 * Every item is self-contained. The house rules are repeated in each
 * one rather than stated once at the top, because these get pasted a
 * few at a time and a rule in a preamble the model never saw is a rule
 * that is not applied. The repetition is the point.
 * ------------------------------------------------------------------ */

const RULES =
  "Plain pure white background. Flat lay, garment square to the frame, filling the frame with a small even margin. " +
  "Soft even studio light, no harsh shadow, no props, no mannequin, no model, no hanger. " +
  "Absolutely no logo, no brand mark, no licensed graphic, no printed or embroidered text, no hangtag, no swing ticket, " +
  "no visible writing of any kind anywhere in the image. Photorealistic product photography. Square 1:1, 3000x3000.";

const SCENE_RULES =
  "Photorealistic, natural light, documentary style. No identifiable person and no recognisable face. " +
  "No company name, no signage, no logo, no brand mark, no visible writing anywhere in the image.";

let txt = "";
txt += "AHM INTERNATIONAL - IMAGE PROMPTS\n";
txt += `${total} images. Generate one at a time and save each using the FILE name given.\n`;
txt += "Every prompt already contains the rules. Do not shorten them - the no-logo rule is why\n";
txt += "35 photographs had to be deleted from this site.\n";
txt += "\n" + "=".repeat(78) + "\n";
txt += `PART 1 OF 3 - ARTICLE PHOTOGRAPHS (${articles.length}) - DO THESE FIRST\n`;
txt += "=".repeat(78) + "\n\n";

let n = 0;
for (const a of articles) {
  n += 1;
  txt += `${n}. FILE: ${master(a.src)}\n`;
  txt += `PROMPT: Product photograph of ${article(a.name)} ${a.name.toLowerCase()}`;
  txt += visualNote(a.note);
  txt += `. ${RULES}\n\n`;
}

txt += "=".repeat(78) + "\n";
txt += `PART 2 OF 3 - PRODUCTION SAMPLES (${strip.length})\n`;
txt += "=".repeat(78) + "\n\n";

for (const [family, items] of byFamily) {
  txt += `-- ${family} --\n\n`;
  for (const item of items) {
    n += 1;
    txt += `${n}. FILE: ${master(item.src)}\n`;
    const subject = plainSubject(item.alt).toLowerCase();
    txt += `PROMPT: Product photograph of ${article(subject)} ${subject}. ${RULES}\n\n`;
  }
}

txt += "=".repeat(78) + "\n";
txt += `PART 3 OF 3 - FACTORY AND ENVIRONMENT SCENES (${other.length})\n`;
txt += "=".repeat(78) + "\n\n";
txt += "These are scenes, not garments. They must never be presented as proof of a real\n";
txt += "facility, a real shipment or a real production run.\n\n";

for (const o of other) {
  n += 1;
  const portrait = o.src.includes("/industries/");
  txt += `${n}. FILE: ${master(o.src)}\n`;
  txt += `PROMPT: ${o.alt.replace(/\.$/, "")}. ${SCENE_RULES} `;
  txt += portrait ? "Portrait 3:4, 2160x2880.\n\n" : "Landscape 16:9, 3840x2160.\n\n";
}

fs.writeFileSync(path.join(root, "image-prompts.txt"), txt);

fs.writeFileSync(path.join(root, "image-brief.md"), out);
console.log(`image-brief.md + image-prompts.txt written — ${articles.length} articles, ${strip.length} samples, ${other.length} other, ${total} total`);
