#!/usr/bin/env node
/**
 * Asset manifest generator.
 *
 * Walks `public/assets` and writes `data/asset-manifest.ts`, recording for every
 * file that is actually present: its intrinsic dimensions and a tiny inlined blur
 * placeholder.
 *
 * The site is built to ship *before* the full photography library exists. Every
 * semantic asset key in `data/assets.ts` declares the path it expects; this
 * manifest is what tells the runtime whether that path has been filled yet, so a
 * missing photograph renders a neutral empty frame instead of a broken image.
 * Drop the real files in and re-run — no component changes.
 *
 *   npm run assets
 *
 * ffmpeg/ffprobe are used when available for dimensions and blur data. Without
 * them the script still records which files exist, and preserves any blur data
 * previously generated.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const assetsDir = path.join(root, "public", "assets");
const outFile = path.join(root, "data", "asset-manifest.ts");

const IMAGE_EXT = new Set([".webp", ".avif", ".jpg", ".jpeg", ".png", ".svg"]);

function have(bin) {
  try {
    execFileSync(bin, ["-version"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

const hasFfprobe = have("ffprobe");
const hasFfmpeg = have("ffmpeg");

/** Previously generated data, so a run without ffmpeg is non-destructive. */
function readExisting() {
  try {
    const src = fs.readFileSync(outFile, "utf8");
    const json = src.slice(src.indexOf("{"), src.lastIndexOf("}") + 1);
    return JSON.parse(json);
  } catch {
    return {};
  }
}

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (IMAGE_EXT.has(path.extname(entry.name).toLowerCase())) out.push(full);
  }
  return out;
}

function dimensions(file) {
  if (!hasFfprobe) return null;
  try {
    const out = execFileSync(
      "ffprobe",
      ["-v", "error", "-select_streams", "v:0", "-show_entries", "stream=width,height", "-of", "csv=p=0:s=x", file],
      { encoding: "utf8" },
    ).trim();
    const [w, h] = out.split("x").map(Number);
    return Number.isFinite(w) && Number.isFinite(h) && w > 0 && h > 0 ? { width: w, height: h } : null;
  } catch {
    return null;
  }
}

/** A 16px-wide WebP, inlined. Large enough to hint at the image, ~200 bytes. */
function blurDataUrl(file) {
  if (!hasFfmpeg) return null;
  const tmp = path.join(root, ".asset-blur.tmp.webp");
  try {
    execFileSync(
      "ffmpeg",
      ["-v", "error", "-y", "-i", file, "-vf", "scale=16:-1:flags=bilinear", "-c:v", "libwebp", "-q:v", "24", tmp],
      { stdio: "ignore" },
    );
    const b64 = fs.readFileSync(tmp).toString("base64");
    return `data:image/webp;base64,${b64}`;
  } catch {
    return null;
  } finally {
    fs.rmSync(tmp, { force: true });
  }
}

if (!fs.existsSync(assetsDir)) {
  fs.mkdirSync(assetsDir, { recursive: true });
}

const previous = readExisting();
const manifest = {};

for (const file of walk(assetsDir).sort()) {
  const key = "/" + path.relative(path.join(root, "public"), file).split(path.sep).join("/");
  const prior = previous[key];
  const dim = dimensions(file) ?? (prior ? { width: prior.width, height: prior.height } : null);
  const isSvg = path.extname(file).toLowerCase() === ".svg";

  manifest[key] = {
    width: dim?.width ?? 0,
    height: dim?.height ?? 0,
    // SVGs are already tiny and blur poorly; they get no placeholder.
    blur: isSvg ? null : (blurDataUrl(file) ?? prior?.blur ?? null),
  };
}

const banner = `// AUTO-GENERATED by scripts/scan-assets.mjs — do not edit by hand.
// Regenerate with: npm run assets
//
// Records every image currently present under public/assets. Semantic keys in
// data/assets.ts consult this to decide between a real image and a neutral
// missing-asset fallback.

export type ManifestEntry = {
  width: number;
  height: number;
  blur: string | null;
};

export const assetManifest: Record<string, ManifestEntry> = `;

fs.writeFileSync(outFile, `${banner}${JSON.stringify(manifest, null, 2)};\n`);

const count = Object.keys(manifest).length;
console.log(
  `assets: ${count} file${count === 1 ? "" : "s"} indexed -> data/asset-manifest.ts` +
    (hasFfmpeg ? "" : "  (ffmpeg not found — blur data preserved from previous run)"),
);
